# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.0.0a1.dev0+g1266066.d20230806'
__version_tuple__ = version_tuple = (1, 0, 0, 'dev0', 'g1266066.d20230806')
